### ISSUE TITLE
Deck should include discard pile

### ISSUE THREAD

**Issue by ThunderDev1** [3-Devs-1-Bug/bursting-felines#27]
The deck and discard pile are actually the same thing, to ensure that we never run out of cards.
This should be taken into account when shuffling, re-inserting perish and so on.
ie. copy cards from discard to deck when doing these actions (just leave the top discard out of it).

**Comment by hissalht** [comment]
Pretty sure this is wrong. Its not possible to reach the end of the deck, since there always are `n - 1` Perish cards in the deck (`n` being the number of live players).

In fact, having to worry about the deck getting smaller, increasing your chances to draw a Perish card, is one the core mechanics of thie game.
